kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: publish_agent
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/smtp2tg
    username:
      from_secret: docker_username
    build_args:
      - arch=arm

  when:
    event:
    - push
    - tag

---

kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: publish_agent
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/smtp2tg
    username:
      from_secret: docker_username
    build_args:
      - arch=aarch64

  when:
    event:
    - push
    - tag

---

kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: publish_agent
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/smtp2tg
    username:
      from_secret: docker_username
    build_args:
      - arch=amd64

  when:
    event:
    - push
    - tag

---

kind: pipeline
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: dungtri/smtp2tg
    template: dungtri/smtp2tg:OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64
