kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: linux-arm
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/smtp2tg
    username:
      from_secret: docker_username
    build_args:
      - arch=arm

  when:
    event:
    - push
    - tag

---

kind: pipeline
name: aarch64

platform:
  os: linux
  arch: arm64

steps:
- name: linux-arm64
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-aarch64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/smtp2tg
    username:
      from_secret: docker_username
    build_args:
      - arch=aarch64

  when:
    event:
    - push
    - tag

---

kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: linux-amd64
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/smtp2tg
    username:
      from_secret: docker_username
    build_args:
      - arch=amd64

  when:
    event:
    - push
    - tag

---

kind: pipeline
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

depends_on:
  - linux-amd64
  - linux-arm
  - linux-arm64

